json.id contact.id
json.first_name contact.first_name
json.middle_name contact.middle_name
json.last_name contact.last_name
json.full_name contact.full_name
json.bio contact.bio
json.email contact.email
json.phone_number contact.japan_phone
json.date_updated contact.friendly_updated_at